{
    "name": "Custom Discuss Gmail Integration",
    "version": "1.0",
    "summary": "Extend Discuss module with Gmail inbox integration",
    "description": "Fetch and display Gmail inbox messages in the Discuss module",
    "author": "Your Name",
    "website": "https://crm2.wsoftpro.com",
    "category": "Communication",
    "depends": [
        "mail",
        "bus",
        "crm",
        "hr",
    ],
    "external_dependencies": {"python": ["beautifulsoup4", "lxml", "requests"]},
    "qweb": [
        "static/src/xml/mail_thread.xml",
    ],
    "data": [
        "security/ir.model.access.csv",
        "views/discuss_view.xml",
        "data/ir_cron.xml",
        "views/GmailAccount_view.xml",
        "views/gmail_templates.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "custom_gmail/static/src/css/loading.css",
            "custom_gmail/static/src/css/gmail_inbox.css",
            "custom_gmail/static/src/css/compose_modal.css",
            "custom_gmail/static/src/css/gmail_attachment.css",
            "custom_gmail/static/src/css/form_provider.css",
            "custom_gmail/static/src/js/GmailInbox.js",
            "custom_gmail/static/src/js/state.js",
            "custom_gmail/static/src/js/functions/loadMessages.js",
            "custom_gmail/static/src/js/functions/toggleStar.js",
            "custom_gmail/static/src/js/functions/onReply.js",
            "custom_gmail/static/src/js/functions/onReplyAll.js",
            "custom_gmail/static/src/js/functions/onAnalyze.js",
            "custom_gmail/static/src/js/functions/onForward.js",
            "custom_gmail/static/src/js/functions/openComposeModal.js",
            "custom_gmail/static/src/js/functions/fillComposeForm.js",
            "custom_gmail/static/src/js/functions/onSendEmail.js",
            "custom_gmail/static/src/js/functions/index.js",
            "custom_gmail/static/src/js/functions/addGmail.js",
            "custom_gmail/static/src/js/functions/onSnooze.js",
            "custom_gmail/static/src/js/uiUtils.js",
            "custom_gmail/static/src/js/storageUtils.js",
            "custom_gmail/static/src/js/ckeditor.js",
            "custom_gmail/static/src/js/template.js",
            "custom_gmail/static/src/js/upload_adapter.js",
        ]
    },
    # "post_init_hook": "post_init_hook",
    "installable": True,
    "application": False,
}
