version: "3.8"

services:
  db:
    image: postgres:15
    container_name: odoo18-db
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: odoodb18
      TZ: Asia/Bangkok
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U odoo -d ${POSTGRES_DB:-odoodb18}"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  odoo:
    image: odoo:18.0
    container_name: odoo18
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8070:8069"
    environment:
      - TZ=Asia/Bangkok
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./extra-addons:/mnt/extra-addons
    restart: unless-stopped

volumes:
  odoo-data:
  db-data:
