INDUSTRY_SELECTION = [
    ('accounting', 'Accounting'),
    ('airlines_aviation', 'Airlines/Aviation'),
    ('alternative_dispute_resolution', 'Alternative Dispute Resolution'),
    ('alternative_medicine', 'Alternative Medicine'),
    ('animation', 'Animation'),
    ('apparel_fashion', 'Apparel & Fashion'),
    ('architecture_planning', 'Architecture & Planning'),
    ('arts_crafts', 'Arts and Crafts'),
    ('automotive', 'Automotive'),
    ('aviation_aerospace', 'Aviation & Aerospace'),
    ('banking', 'Banking'),
    ('biotechnology', 'Biotechnology'),
    ('broadcast_media', 'Broadcast Media'),
    ('building_materials', 'Building Materials'),
    ('business_supplies_equipment', 'Business Supplies and Equipment'),
    ('capital_markets', 'Capital Markets'),
    ('chemicals', 'Chemicals'),
    ('civic_social_organization', 'Civic & Social Organization'),
    ('civil_engineering', 'Civil Engineering'),
    ('commercial_real_estate', 'Commercial Real Estate'),
    ('computer_networking', 'Computer Networking'),
    ('computer_software', 'Computer Software'),
    ('construction', 'Construction'),
    ('consumer_electronics', 'Consumer Electronics'),
    ('consumer_goods', 'Consumer Goods'),
    ('consumer_services', 'Consumer Services'),
    ('cosmetics', 'Cosmetics'),
    ('dairy', 'Dairy'),
    ('defense_space', 'Defense & Space'),
    ('design', 'Design'),
    ('education_management', 'Education Management'),
    ('e_learning', 'E-Learning'),
    ('electrical_electronic_manufacturing', 'Electrical/Electronic Manufacturing'),
    ('entertainment', 'Entertainment'),
    ('environmental_services', 'Environmental Services'),
    ('events_services', 'Events Services'),
    ('executive_office', 'Executive Office'),
    ('facilities_services', 'Facilities Services'),
    ('farming', 'Farming'),
    ('financial_services', 'Financial Services'),
    ('fine_art', 'Fine Art'),
    ('fishery', 'Fishery'),
    ('food_beverages', 'Food & Beverages'),
    ('food_production', 'Food Production'),
    ('fundraising', 'Fund-Raising'),
    ('furniture', 'Furniture'),
    ('gambling_casinos', 'Gambling & Casinos'),
    ('glass_ceramics_concrete', 'Glass, Ceramics & Concrete'),
    ('government_administration', 'Government Administration'),
    ('government_relations', 'Government Relations'),
    ('graphic_design', 'Graphic Design'),
    ('health_wellness_fitness', 'Health, Wellness and Fitness'),
    ('higher_education', 'Higher Education'),
    ('hospital_healthcare', 'Hospital & Health Care'),
    ('hospitality', 'Hospitality'),
    ('human_resources', 'Human Resources'),
    ('import_export', 'Import and Export'),
    ('individual_family_services', 'Individual & Family Services'),
    ('industrial_automation', 'Industrial Automation'),
    ('information_services', 'Information Services'),
    ('information_technology_services', 'Information Technology and Services'),
    ('insurance', 'Insurance'),
    ('international_affairs', 'International Affairs'),
    ('international_trade', 'International Trade and Development'),
    ('internet', 'Internet'),
    ('investment_banking', 'Investment Banking'),
    ('investment_management', 'Investment Management'),
    ('judiciary', 'Judiciary'),
    ('law_enforcement', 'Law Enforcement'),
    ('law_practice', 'Law Practice'),
    ('legal_services', 'Legal Services'),
    ('legislative_office', 'Legislative Office'),
    ('leisure_travel_tourism', 'Leisure, Travel & Tourism'),
    ('libraries', 'Libraries'),
    ('logistics_supply_chain', 'Logistics and Supply Chain'),
    ('luxury_goods_jewelry', 'Luxury Goods & Jewelry'),
    ('machinery', 'Machinery'),
    ('management_consulting', 'Management Consulting'),
    ('maritime', 'Maritime'),
    ('marketing_advertising', 'Marketing and Advertising'),
    ('market_research', 'Market Research'),
    ('mechanical_industrial_engineering', 'Mechanical or Industrial Engineering'),
    ('media_production', 'Media Production'),
    ('medical_device', 'Medical Device'),
    ('medical_practice', 'Medical Practice'),
    ('mental_health_care', 'Mental Health Care'),
    ('military', 'Military'),
    ('mining_metals', 'Mining & Metals'),
    ('motion_pictures_film', 'Motion Pictures and Film'),
    ('museums_institutions', 'Museums and Institutions'),
    ('music', 'Music'),
    ('nanotechnology', 'Nanotechnology'),
    ('newspapers', 'Newspapers'),
    ('nonprofit', 'Nonprofit Organization Management'),
    ('oil_energy', 'Oil & Energy'),
    ('online_media', 'Online Media'),
    ('outsourcing_offshoring', 'Outsourcing/Offshoring'),
    ('packaging_containers', 'Packaging and Containers'),
    ('paper_forest_products', 'Paper & Forest Products'),
    ('performing_arts', 'Performing Arts'),
    ('pharmaceuticals', 'Pharmaceuticals'),
    ('philanthropy', 'Philanthropy'),
    ('photography', 'Photography'),
    ('plastics', 'Plastics'),
    ('political_organization', 'Political Organization'),
    ('primary_secondary_education', 'Primary/Secondary Education'),
    ('printing', 'Printing'),
    ('professional_training', 'Professional Training & Coaching'),
    ('program_development', 'Program Development'),
    ('public_policy', 'Public Policy'),
    ('public_relations', 'Public Relations and Communications'),
    ('public_safety', 'Public Safety'),
    ('publishing', 'Publishing'),
    ('railroad_manufacture', 'Railroad Manufacture'),
    ('ranching', 'Ranching'),
    ('real_estate', 'Real Estate'),
    ('recreational_facilities_services', 'Recreational Facilities and Services'),
    ('religious_institutions', 'Religious Institutions'),
    ('renewables_environment', 'Renewables & Environment'),
    ('research', 'Research'),
    ('restaurants', 'Restaurants'),
    ('retail', 'Retail'),
    ('security_investigations', 'Security and Investigations'),
    ('semiconductors', 'Semiconductors'),
    ('shipbuilding', 'Shipbuilding'),
    ('sporting_goods', 'Sporting Goods'),
    ('sports', 'Sports'),
    ('staffing_recruiting', 'Staffing and Recruiting'),
    ('supermarkets', 'Supermarkets'),
    ('telecommunications', 'Telecommunications'),
    ('textiles', 'Textiles'),
    ('think_tanks', 'Think Tanks'),
    ('tobacco', 'Tobacco'),
    ('translation_localization', 'Translation and Localization'),
    ('transportation_trucking', 'Transportation/Trucking/Railroad'),
    ('utilities', 'Utilities'),
    ('venture_capital_private_equity', 'Venture Capital & Private Equity'),
    ('veterinary', 'Veterinary'),
    ('warehousing', 'Warehousing'),
    ('wholesale', 'Wholesale'),
    ('wine_spirits', 'Wine and Spirits'),
    ('wireless', 'Wireless'),
    ('writing_editing', 'Writing and Editing'),
]